### ISSUE TITLE
Smiles parser fails

### ISSUE THREAD

**Issue by proteneer** [chemplexity/molecules#1]
c1ccccc1[C@]2(C(=O)N(C)C(N)=[NH+]2)c3cc(ccc3)-c4ccc(cc4)OC

Uncaught TypeError: Cannot read property 'output' of undefined

**Comment by proteneer** [comment]
another use case

C1CCCC1

Then this fails:

if (findObjects(grammar.atoms, 'symbol', input[input.length-1]) == null) return false;

**Comment by chemplexity** [comment]
Thanks for reporting those. Looks like it was an issue with associating ring and chirality symbols with the correct atom. I should have a fix for that soon.

**Comment by proteneer** [comment]
Thanks for looking into it.

**Comment by chemplexity** [comment]
- C1CCCC1

Fixed a number of issues with ring notations. This string gives the correct output now.

- c1ccccc1[C@]2(C(=O)N(C)C(N)=[NH+]2)c3cc(ccc3)-c4ccc(cc4)OC

Output I'm getting is C23, H22, N3, O2 (372.44 g/mol). Same structure and mass as the ChemDraw interpretation of this string, so I will assume this is resolved now.

![image](https://cloud.githubusercontent.com/assets/5705840/26371595/2cf8ebd4-3fc9-11e7-8e1c-5044d0e7be48.png)
